language: cpp

branches:
  only:
    - master

os:
  - linux

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt521
 - sudo apt-get -qy update
 - sudo apt-get -qy install qt52base qt52tools

script:
 - source /opt/qt52/bin/qt52-env.sh
 - lrelease res/lang/en.ts
 - qmake apkstudio.pro CONFIG+=release
 - make
